# Generated by Django 5.1.7 on 2025-03-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='price',
            new_name='price_in_usd',
        ),
    ]
