# Generated by Django 5.1.7 on 2025-03-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_alter_laptop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Business', 'Business'), ('Budget', 'Budget'), ('Ultrabooks', 'Ultrabooks')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
